### ISSUE TITLE
install log.h

### ISSUE THREAD

**Issue by stdweird** [adaptivecomputing/torque#166]
log.h is not installed as part of the include files, making pbs_log.h from Liblog useless (log.h needs to be moved in src/include/Makefile.am from noinst_HEADERS to include_HEADERS)

**Comment by boegel** [comment]
This problem occurs again (at least on the current 5.1-dev branch).

`log.h` is relied upon by `pbs_python` (https://oss.trac.surfsara.nl/pbs_python), and I'm getting this when trying to build/install pbs_python with `log.h` missing:

```
Failed to find log.h in include dir /usr/include/torque. (Set include dir via PBS_PYTHON_INCLUDEDIR variable)
```

Can this please be (re)fixed?

cc @itkovian

**Comment by itkovian** [comment]
Problem seems to be introduced in commit 2811f610db7. At least for log.h.

**Comment by knielson** [comment]
b3ec322..20f67a7  5.1-dev -> 5.1-dev
205d70d..0aab00c  5.1.3 -> 5.1.3
63f107b..2144daa  6.0-dev -> 6.0-dev
3a9c186..fe6243b  develop -> develop

**Comment by knielson** [comment]
Fixed with the above commits

**Comment by boegel** [comment]
Thanks @knielson!
