### ISSUE TITLE
Incorrect qstat output

### ISSUE THREAD

**Issue by mathera** [adaptivecomputing/torque#223]
Hi,

We're in the process of configuring our new Torque (4.2.7) and have come up with an issue.

Our previous install (2.5.1) has output as below:

[root@dev1 ~]# qstat -a

mgt-mgmt.basc.dpi.vic.gov.au:
                                                                         Req'd  Req'd   Elap
Job ID               Username Queue    Jobname          SessID NDS   TSK Memory Time  S Time
-------------------- -------- -------- ---------------- ------ ----- --- ------ ----- - -----
2218246.mgt-mgmt     ss1b     batch    MIRA_4-2014         --      1   8  800gb 1200: Q   --
2500686.mgt-mgmt     sk00     batch    Trinity.fasta.ca   6105     1   6   22gb 170:0 R 141:0
2502414.mgt-mgmt     im18     batch    FG_BN_Job25       13862     1   1   18gb 45:00 R 25:26
2502516.mgt-mgmt     jp24     asreml   RFI_validation    16526   --   -- 13800m 40:00 R 22:49

qstat-f on one of these jobs (2502414) shows
    Resource_List.mem = 18gb
    Resource_List.nodect = 1
    Resource_List.nodes = 1
    Resource_List.pmem = 3800mb

The new (4.2.7) shows:

[root@dev3 NCBI]# qstat -a

mgt.basc.science.depi.vic.gov.au:
                                                                                  Req'd    Req'd       Elap
Job ID                  Username    Queue    Jobname          SessID  NDS   TSK   Memory   Time    S   Time
----------------------- ----------- -------- ---------------- ------ ----- ------ ------ --------- - ---------
187.mgt.basc.science.d  pb26        batch    samtools_4        43945     1      1  3800m  02:00:00 R  00:34:08
188.mgt.basc.science.d  pb26        batch    samtools_5        43906     1      1  3800m  02:00:00 R  00:34:07
189.mgt.basc.science.d  pb26        batch    samtools_6        43792     1      1  3800m  02:00:00 R  00:34:07
190.mgt.basc.science.d  pb26        batch    samtools_7        43880     1      1  3800m  02:00:00 R  00:34:06
192.mgt.basc.science.d  pb26        batch    samtools_9        43180     1      1  3800m  02:00:00 R  00:34:05
193.mgt.basc.science.d  pb26        batch    samtools_10       43945     1      1  3800m  02:00:00 R  00:34:04
226.mgt.basc.science.d  pb26        batch    memstress_33      44137     1      1  3800m  06:00:00 R  00:04:26
227.mgt.basc.science.d  pb26        batch    memstress_34      44209     1      1  3800m  06:00:00 R  00:01:37
228.mgt.basc.science.d  pb26        batch    memstress_35      44178     1      1  3800m  06:00:00 R  00:01:06
229.mgt.basc.science.d  pb26        batch    memstress_36      44192     1      1  3800m  06:00:00 R  00:01:06
230.mgt.basc.science.d  pb26        batch    memstress_37      44234     1      1  3800m  06:00:00 R  00:01:06
231.mgt.basc.science.d  pb26        batch    memstress_38      46662     1      1  3800m  06:00:00 R  00:00:35

qstat -f on one of these jobs (226) shows:
        Resource_List.mem = 376gb
    Resource_List.nodect = 1
    Resource_List.nodes = 1:ppn=1
    Resource_List.pmem = 3800mb
    Resource_List.walltime = 06:00:00

It seems that the newer version is showing the value of the Resource_List.pmem field (which is the default value for the queue)

**Comment by knielson** [comment]
I don't understand the issue. The Resource_List.pmem=3800mb appears to be the same for both outputs. I do see a difference between the Resource_List.nodes output.

**Comment by mathera** [comment]
Hi Ken,

The issue is that the previous qstat output used the value for
Resource_List.mem,
while the newer version used the value for Resource_List.pmem.

At our site, users specify mem rather than pmem, as we do not enforce
memory limits, we only use them as a guide and the qstat output is parsed
and used for various in-house web pages that people use to watch their jobs
flow through the system. This made the output much less useful for our site
and broke a number of in-house scripts.

However, since this ticket was opened, we have moved on and it is no longer
an issue with the 4.2.9 that we're now using.

Andrew

On Wed, Sep 2, 2015 at 12:53 AM, Ken Nielson <notifications@github.com>
wrote:

> I don't understand the issue. The Resource_List.pmem=3800mb appears to be
> the same for both outputs. I do see a difference between the
> Resource_List.nodes output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adaptivecomputing/torque/issues/223#issuecomment-136750328>
> .
>



-- 
-
http://surfcoast.redbubble.com |
https://picasaweb.google.com/107747436224613508618
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
"Unless someone like you, cares a whole awful lot, nothing is going to get
better...It's not !" - The Lorax
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
A committee is a cul-de-sac, down which ideas are lured and then quietly
strangled.
  *Sir Barnett Cocks
<http://www.quotationspage.com/quotes/Sir_Barnett_Cocks/>*
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
"A mind is like a parachute. It doesnt work if it's not open." :- Frank
Zappa
-

**Comment by knielson** [comment]
Thanks for responding. I will close this issue
