### ISSUE TITLE
Prologue exit 2 Does Not Report ERROR

### ISSUE THREAD

**Issue by victorgregorio** [adaptivecomputing/torque#241]
Seen in TORQUE 4.2.8 and 4.2.6.1

With a prologue and prologue.parallel set to only exit 2 for testing:

```
#!/bin/bash

exit 2
```

...running a single node job causes the job to re-queue after the prologue exit 2 as expected.  Unfortunately, no error message is shown in pbsnodes and consequently, Moab does not see the error and mark the node as Down as expected with the default setting of:

```
RMMSGIGNORE     FALSE
```

On the other hand, a multi-node jobs that kicks off prologue.parallel on sister nodes behaves as expected.  The jobs re-queues, pbsnodes shows the ERROR (for only sister nodes) and Moab marks the node as Down.  The mother superior running prologue still does not report an error, though.

```
n1
     state = free
     np = 4
     ntype = cluster
     status = rectime=1405958542,varattr=,jobs=,state=free,netload=2610510775,gres=,message=
ERROR: prolog/epilog failed,file: /var/spool/torque/mom_priv/prologue.parallel,exit: 2,nonze
ro p/e exit status,loadave=0.04,ncpus=4,physmem=6122160kb,availmem=5944972kb,totmem=6122160k
b,idletime=205107266,nusers=0,nsessions=0,uname=Linux n1 2.6.32-431.20.3.el6.656a0000.x86_64
 #1 SMP Fri Jun 20 04:00:53 EDT 2014 x86_64,opsys=linux
     mom_service_port = 15002
     mom_manager_port = 15003
```

Running strace on pbs_mom showed EAGAIN (Resource temporarily unavailable) messages on mother superior nodes after running prologue that did not occur on sister nodes after running prologue.parallel:  

```
34748 fcntl(8, F_GETFL)                 = 0x802 (flags O_RDWR|O_NONBLOCK)
34748 read(8, 0x7fffb6715d80, 65536)    = -1 EAGAIN (Resource temporarily unavailable)
34748 read(8, 0x7fffb6715d80, 65536)    = -1 EAGAIN (Resource temporarily unavailable)
34748 read(8, 0x7fffb6715d80, 65536)    = -1 EAGAIN (Resource temporarily unavailable)
34748 read(8, 0x7fffb6715d80, 65536)    = -1 EAGAIN (Resource temporarily unavailable)
34748 read(8, 0x7fffb6715d80, 65536)    = -1 EAGAIN (Resource temporarily unavailable)
34748 read(8, 0x7fffb6715d80, 65536)    = -1 EAGAIN (Resource temporarily unavailable)
34748 read(8, 0x7fffb6715d80, 65536)    = -1 EAGAIN (Resource temporarily unavailable)
34748 read(8, 0x7fffb6715d80, 65536)    = -1 EAGAIN (Resource temporarily unavailable)
```

I hope this helps!

**Comment by acvizi** [comment]
Prologue failures don't report a node down; you should use a compute node health check script for node issues, and use the prologue script to see whether or not a job can run. Information about the node health check script can be found in the TORQUE documentation. If you wish to have the node health check script run at job start and/or job end time, take a look at the "node_check_interval" MOM parameter.
