### ISSUE TITLE
environment variables when specifying nodename

### ISSUE THREAD

**Issue by stdweird** [adaptivecomputing/torque#299]
when submitting a job with `-l nodes=fullnodename:ppn=16`, some of the the environment variables are wrong. in particular `PBS_NUM_PPN` is set to 1 instead of 16, and also `PBS_NUM_NODES` is 0 instead of expected 1.

ran into this on 4.2-dev and 5.1-dev

**Comment by dbeer** [comment]
This should be fixed in 5.1.1 and 5.0.2.

**Comment by stdweird** [comment]
verified. @dbeer thx!
