### ISSUE TITLE
Installing Torque in dell computer with 8 nodes and 64 cores in Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by leirhyh** [adaptivecomputing/torque#300]
Hi,
I have two dell computer with 8 nodes and 64 cores, 2 nodes and 32 cores in Ubuntu 14.04 LTS.
When I tried to install Torque for couple of times, I get the following errors.
Could you help fix this issues?
My installing process is as follows:
genetics@genetics2:/software/torque-4.2.6.1$ ./configure --prefix=/usr/local/torque
Building components: server=yes mom=yes clients=yes
                     gui=no drmaa=no pam=no
PBS Machine type    : linux
Remote copy         : /usr/bin/scp -rpB
PBS home            : /var/spool/torque
Default server      : genetics2

Unix Domain sockets : 
Linux cpusets       : no
Tcl                 : disabled
Tk                  : disabled

Ready for 'make'.

genetics@genetics2:/software/torque-4.2.6.1$ make

make[1]: Leaving directory `/software/torque-4.2.6.1/contrib/init.d'
make[1]: Entering directory `/software/torque-4.2.6.1'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/software/torque-4.2.6.1'

sudo make install
make[3]: Entering directory `/software/torque-4.2.6.1'
make[3]: Nothing to be done for `install-data-hook'.
make[3]: Leaving directory `/software/torque-4.2.6.1'
make[2]: Leaving directory `/software/torque-4.2.6.1'
make[1]: Leaving directory `/software/torque-4.2.6.1'

genetics@genetics2:/software/torque-4.2.6.1$ vim /etc/profile
genetics@genetics2:/software/torque-4.2.6.1$ sudo -s
root@genetics2:/software/torque-4.2.6.1# source /etc/profile

root@genetics2:/software/torque-4.2.6.1# sudo ./torque.setup root
initializing TORQUE (admin: root@genetics2)
./torque.setup: 45: ./torque.setup: pbs_server: not found
ERROR: pbs_server failed to start, check syslog and server logs for more information

root@genetics2:/software/torque-4.2.6.1# touch /etc/profile.d/torque.sh
root@genetics2:/software/torque-4.2.6.1# vim /etc/profile.d/torque.sh
root@genetics2:/software/torque-4.2.6.1# source /etc/profile.d/torque.sh
root@genetics2:/software/torque-4.2.6.1# sudo ./torque.setup root
initializing TORQUE (admin: root@genetics2)
./torque.setup: 45: ./torque.setup: pbs_server: not found
ERROR: pbs_server failed to start, check syslog and server logs for more information
 Could you give me some advice on how to install Torque in Ubuntu?

Thanks a bunch,

All the best,

Runhua

**Comment by knielson** [comment]
You will need to to run autogen.sh before you run configure. With Ubuntu 14.04 I also suggest you use the 4.2.10 or later versions of TORQUE because the configure.ac files previous to those builds will now work the the new autotools in Ubuntu 14.04

**Comment by leirhyh** [comment]
Hi Ken:
Thanks and I appreciate your time.

All the best,

Runhua
