### ISSUE TITLE
pbs_mom daemons should write the parent pid to file

### ISSUE THREAD

**Issue by stdweird** [adaptivecomputing/torque#302]
It's not easy to determine if a pbs_mom service running, because pbs_mom can spawn multiple instances of the pbs_mom process.
This makes it hard to check if the service is alive (see e.g. #288 )  

It would be beneficial if pbs_mom would write the parent (or whatever the service process is called) wites its pid to a file (eg. the `mom.lock` or another file).

**Comment by knielson** [comment]
Stijn,

It turns out the mom.lock file has the pid of the pbs_mom daemon. You can use that file to make sure you have the right pid.  You can also use momctl -s. Of course that won't work with an unresponive pbs_mom.

**Comment by stdweird** [comment]
@knielson thanks. so we get all pbs_mom pids, and if those pids there is not one corresponding with the one in the mom.lock, the parent is not running anymore? 
there's ofcourse a small chance that a child pbs_mom got cycled to reach the one in the mom.lock...

@itkovian lets check for pbs_mom pids that have an open fd to the mom.lock

**Comment by itkovian** [comment]
Done.
