### ISSUE TITLE
job with after dependency gets removed when at end of depending job

### ISSUE THREAD

**Issue by stdweird** [adaptivecomputing/torque#303]
using torque 5.1-dev (with https://github.com/adaptivecomputing/torque/commit/2850e30c1d242c6804fef1cc2eb25108cbcdc600), we have the following behaviour, which i suspect is a bug:

a. qsub job_sleep100.sh -> jobid 1
b. qsub -W after:1 job_sleep500.sh -> jobid 2

job 1 and job 2 start (2 after 1 is started), when job 1 is finished, job 2 gets deleted/removed.

we expect from the description in the manual however that the after dependency only has influence on the start of job 2.

**Comment by dbeer** [comment]
This should be fixed with commit 25244181211

**Comment by stdweird** [comment]
seems fixed. @dbeer thanks
