### ISSUE TITLE
Failed to compile qstat.c with tcl8.6

### ISSUE THREAD

**Issue by orex** [adaptivecomputing/torque#305]
If tcl is enabled,  `make` stops with the following errors 

qstat.c: In function ‘void tcl_init()’:
qstat.c:2219:21: error: ‘Tcl_Interp’ has no member named ‘result’
             interp->result);
                     ^
qstat.c: In function ‘void tcl_run(int)’:
qstat.c:2348:23: error: ‘Tcl_Interp’ has no member named ‘result’
       trace = interp->result;
                       ^
qstat.c:2351:29: error: ‘Tcl_Interp’ has no member named ‘errorLine’
             script, interp->errorLine, trace);

The reason for this error is that interp->result/errorLine were deprecated in tcl8.5 and removed in the 8.6 version.

The workaround is to add 2 lines before #include <tcl.h>, which enables deprecated options
#if TCL_QSTAT
+#define USE_INTERP_RESULT 
+#define USE_INTERP_ERRORLINE
#include <sys/stat.h>
#include <tcl.h>

The similar problem is also appears in tcl scheduler.

**Comment by knielson** [comment]
If you can fix this problem I would recommend you do so and create a pull request.

**Comment by shlomif** [comment]
It seems that the code in commit bdfc742d1c75e5db35b13ae7b55f1c756b2b5457 already handles this properly:

```
#if ((TCL_MAJOR_VERSION < 8) || ((TCL_MAJOR_VERSION == 8) && \
    (TCL_MINOR_VERSION < 6))) && (!defined(Tcl_GetErrorLine))
#define Tcl_GetErrorLine(interp) (interp->errorLine)
#endif

```

So I suggest this bug gets closed as FIXED.

**Comment by dbeer** [comment]
Yes, I believe this is addressed.

**Comment by shlomif** [comment]
@dbeer : thanks!
