### ISSUE TITLE
Torque 5.1 scheduler won't invoke FIFO scheduling

### ISSUE THREAD

**Issue by byron3** [adaptivecomputing/torque#310]
Torque 5.1 won't employ FIFO scheduling even if 

strict_fifo: true ALL

is set in the sched_config file.

**Comment by knielson** [comment]
An internal ticket has been created for this issue.

**Comment by knielson** [comment]
Fixed in the following branches

98ebf9b..bb93500 5.1-dev -> 5.1-dev
4b458a3..3daaa03 5.0-dev -> 5.0-dev
11c90ce..486c52b develop -> develop

**Comment by byron3** [comment]
Ken,

Can you please send me instructions for downloading the patched version of 5.1.

I imagine I am not picking-up the patched version.

Thanks
Byron

**Comment by knielson** [comment]
Byron,

You will need to create your own patch. The commit to 5.1-dev is commit
bb935006b1dbaa9e0dd88e19ee9eb92ddc252105. It was commited on May 8, 2015.
You can do a git diff on that commit and the one before and it will create
a patch file for you. To save you time I have written the git diff below.

git diff 98ebf9b120b3ec7c8d4af8b7a0ca2b3aad1523cf
bb935006b1dbaa9e0dd88e19ee9eb92ddc252105

Redirect that to a file and then you can patch it to your 5.1 code using
patch -p1 < diff_file_name

Let me know if you have any questions.

Ken

On Thu, May 28, 2015 at 6:59 PM, byron3 <notifications@github.com> wrote:

> Ken,
>
> Can you please send me instructions for downloading the patched version of
> 5.1.
>
> I imagine I am not picking-up the patched version.
>
> Thanks
> Byron
>
> From: Ken Nielson [mailto:notifications@github.com]
> Sent: Friday, May 08, 2015 12:06 PM
> To: adaptivecomputing/torque
> Cc: Byron Lengsfield
> Subject: Re: [torque] Torque 5.1 scheduler won't invoke FIFO scheduling
> (#310)
>
>
> Fixed in the following branches
>
> 98ebf9b<
> https://github.com/adaptivecomputing/torque/commit/98ebf9b120b3ec7c8d4af8b7a0ca2b3aad1523cf
> >..bb93500<
> https://github.com/adaptivecomputing/torque/commit/bb935006b1dbaa9e0dd88e19ee9eb92ddc252105>
> 5.1-dev -> 5.1-dev
> 4b458a3<
> https://github.com/adaptivecomputing/torque/commit/4b458a3eff9b30cb6b7d64cad53dc70fe5cce9de
> >..3daaa03<
> https://github.com/adaptivecomputing/torque/commit/3daaa030b95538d1a1fb7b87537e069abb777eb3>
> 5.0-dev -> 5.0-dev
> 11c90ce<
> https://github.com/adaptivecomputing/torque/commit/11c90cec15183569c44263ee8040de832bc716a5
> >..486c52b<
> https://github.com/adaptivecomputing/torque/commit/486c52bbdc4d2ba591d7c780b839c36191b45b5a>
> develop -> develop
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/adaptivecomputing/torque/issues/310#issuecomment-100329985>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adaptivecomputing/torque/issues/310#issuecomment-106644701>
> .
>



-- 
       [image: Adaptive Computing] <http://www.adaptivecomputing.com>
 [image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
 +1 801.717.3700 office    +1 801.717.3738 fax
 1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
 www.adaptivecomputing.com
