### ISSUE TITLE
pbs_environment

### ISSUE THREAD

**Issue by necrolyte2** [adaptivecomputing/torque#311]
I'm having trouble finding information about how to configure  ``pbs_environment``

Which services actually utilize this file? It seems that all daemons at least read this file, but does it get used to setup job environments?

This is the only page in the documentation that I found that had any information about ``pbs_environment``
http://docs.adaptivecomputing.com/8-1-0/basic/help.htm#topics/torque/11-troubleshooting/debugging.htm?Highlight=pbs_environment

Our install did not specify `--with-environ` during the install so our pbs_environment should be under
/var/spool/torque/pbs_environment which there is a file.

What I'm trying to do is to set a variable in pbs_environment such that when non-interactive jobs are run that they would get this variable. Such as ```MYEXAMPLE=/some/path```

It seems that torque is not pulling these variables as when I submit a job such as

```
cat <<EOF | qsub
#!/bin/bash
echo $MYEXAMPLE
EOF
```

Nothing is printed.

I have tried setting pbs_environment on both the host where pbs_server,pbs_sched live as well as pbs_mom

Any help is appreciated

**Comment by necrolyte2** [comment]
Seems I must have not tried restarting pbs_mom before

So adding any variables to ``$PBS_HOME/pbs_environ`` then restarting pbs_mom works

Might be best to add that to the documentation

**Comment by dbeer** [comment]
We have created a documentation ticket to explain how this file is used. In short, it is sourced for pbs_mom, pbs_server, prologue and epilogue scripts, and jobs.

**Comment by dbeer** [comment]
After double-checking the code, it is only sourced by the pbs_mom and pbs_server daemons.
