### ISSUE TITLE
encode any text written to xml

### ISSUE THREAD

**Issue by stdweird** [adaptivecomputing/torque#318]
job attributes are not encoded when written to xml format. in particular, submitting jobs with `-V` can send lots of user-defined stuff, in particular exported functions (since heartbleed, 
```bash
x () {
   echo ok
}
export -f x
```
generates a bash environment variable `BASH_FUNC_x` which contains the function code, which can contain lots of stuff like `&` and `>`.)

a lot of the code uses `xmlNewChild` which specifically states in http://xmlsoft.org/html/libxml-tree.html#xmlNewChild 
```
NOTE: @content is supposed to be a piece of XML CDATA, so it allows entity references. XML special chars must be escaped first by using xmlEncodeEntitiesReentrant(), or xmlNewTextChild() should be used.
```

**Comment by dbeer** [comment]
Stjin,

This has been fixed by https://github.com/adaptivecomputing/torque/commit/f6414c77fc1bafdad8d502e59fd7e26660d82f08. Please re-open this if that doesn't take care of it for you.

**Comment by stdweird** [comment]
@dbeer thx. somehow i overlooked the commit in the commitlog. thanks a lot!

**Comment by stdweird** [comment]
@dbeer can i reopen this issue? the commit that fixes this is lacking unittests. we just had a new batch of problems due to this bug, and it's not that easy to upgrade live for us. this has to be catched by unittests.

**Comment by dbeer** [comment]
You don't need to ask permission. If you are still having issues then there are issues. Can you either attach or email me a job file that fails to load?

**Comment by stdweird** [comment]
@dbeer to be clear, there are no issues (well, except for the old/present jobs), but i would really like to see unittests that can guard this. it's by far one of the easiest ways to cause serious problems, you've been all doing excellent work with unittesting the rest of code, this should have been spotted imho.

**Comment by dbeer** [comment]
No worries, I'll add some unit tests for it. It spans multiple files, so I'll be judicious in how I unit test it.

**Comment by dbeer** [comment]
I added these unit tests but forgot to come back to close this. Any objection to closing now?

**Comment by stdweird** [comment]
@dbeer sure you can close this. maybe mention the commit here?

**Comment by dbeer** [comment]
Here's the commit: 26fe5d229cc36f4fee68661dadf035805428c461
