### ISSUE TITLE
interactive jobs failing 'cannot connect to port 777 ...'

### ISSUE THREAD

**Issue by necrolyte2** [adaptivecomputing/torque#329]
I have pbs_server, pbs_sched and pbs_mom all running on same host for debugging

Trying to run an interactive job fails
```
qsub -q interactive -I
```

If I add a new rule to iptables 
```
iptables -I INPUT -s x.x.x.x -j ACCEPT
```
Where x.x.x.x is ip of pbs_server then the job completes as expected

I'm not the best with tcpdump, but I did run it while I had the above rule that allowed the job to run
```
tcpdump -i any 'not tcp port 22' -v -nn | tee dump-success.txt
```

### The two dump files created(can download and rename to just .txt sorry they are not pcap files)
![dump-success txt](https://cloud.githubusercontent.com/assets/378659/10765810/fb7247b4-7caa-11e5-85d2-e2ff4110def0.png)
![dump-failed txt](https://cloud.githubusercontent.com/assets/378659/10765811/fb725f74-7caa-11e5-92b8-e5adb6145d49.png)

### Extract the used ports reported by tcpdump

```
grep -oE '> (127|x).(0|x).(0|x).(1|x).[0-9]+' dump-success.txt | cut -d' ' -f2 | awk -F'.' '{printf("%s.%s.%s.%s %s\n",$1,$2,$3,$4,$5)}' | sort -n -k2| uniq
x.x.x.x 264
x.x.x.x 503
x.x.x.x 926
x.x.x.x 999
x.x.x.x 1000
x.x.x.x 15001
x.x.x.x 15002
x.x.x.x 15003
x.x.x.x 15004
x.x.x.x 44019
x.x.x.x 45377
x.x.x.x 47847
x.x.x.x 47848
```

```
grep -oE '> (127|x).(0|x).(0|x).(1|x).[0-9]+' dump-failed.txt | cut -d' ' -f2 | awk -F'.' '{printf("%s.%s.%s.%s %s\n",$1,$2,$3,$4,$5)}' | sort -n -k2| uniq
x.x.x.x 333
127.0.0.1 512
x.x.x.x 593
x.x.x.x 617
x.x.x.x 735
x.x.x.x 885
x.x.x.x 886
x.x.x.x 887
x.x.x.x 919
x.x.x.x 923
x.x.x.x 944
x.x.x.x 945
x.x.x.x 946
x.x.x.x 947
x.x.x.x 948
x.x.x.x 15001
x.x.x.x 15002
x.x.x.x 15003
x.x.x.x 15004
x.x.x.x 44856
x.x.x.x 47792
x.x.x.x 47793
x.x.x.x 47794
x.x.x.x 47796
```

### And just to see difference of protocols used for each
```
# grep -oE 'proto [a-zA-Z]+' dump-*txt | sort | uniq
dump-failed.txt:proto ICMP
dump-failed.txt:proto TCP
dump-failed.txt:proto UDP
dump-success.txt:proto TCP
```

## Debugging information

OS: CentOS 6
Torque Ver: 5.1.1.2-1_18e4a5f1

### Full error message from /var/log/messages
```
Oct 27 12:44:23 amedwrair015377 pbs_mom: LOG_ERROR::Operation now in progress (115) in start_interactive_session, cannot open interactive qsub socket to host maskedhost.example.com:40271 - 'cannot connect to port 777 in client_to_svr - errno:115 ' - check routing tables/multi-homed host issues
```

### iptables
```
# iptables -nvL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
  440 35341 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           tcp dpt:15001
  165 10189 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           tcp dpt:15003
   32  4768 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           tcp dpt:15002
   65  3536 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           tcp dpt:15004
  318 20416 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           tcp dpts:256:1024
  595 50500 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           tcp dpt:22
  388  371K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0           state RELATED,ESTABLISHED
    4   198 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0           reject-with icmp-host-prohibited
```

### /etc/hosts(some info is masked)
```
x.x.x.x maskedhost.example.com
```

### /var/spool/torque/server_name
```
maskedhost.example.com
```

I'm not sure how I'm missing which port I need to open in iptables, but I'm sure I'm using tcpdump wrong.
Thanks for any help

**Comment by mattaezell** [comment]
When you issue an interactive qsub, the qsub process will start listening on an ephemeral port.  It will send the hostname and port to pbs_server, which will then dispatch it to the pbs_mom.  The pbs_mom will bind to a privileged port (777 in your case) and then try to connect to the qsub process on the ephemeral port (40271 in your case).  The 'cannot connect to port 777' message is erroneous, and I've made a pull request to fix it.

As for what you need to open, qsub uses bind() specifying port 0, so it's assigned a random port.  Luckily it should come from a privileged port, so you can limit it to that.  If that's a problem with your security policy, then you need to open a feature request to limit what ephemeral port qsub might use.

I usually have my submission hosts on the same network as my cluster with open firewall rules between them.

**Comment by necrolyte2** [comment]
So in theory if I open up 1-1024 then it should work correct?

**Comment by mattaezell** [comment]
No, you would need to open up all destination ports on the hosts running qsub interactively.  You can limit the source IP addresses to the hosts running pbs_mom and the **source** port to 1-1024.

**Comment by necrolyte2** [comment]
I see. Thanks for the info! I had done what you suggested and just allow all traffic between mom->server.

**Comment by stevenweaver** [comment]
In case anyone else comes across this issue, the order in which the host names appear in `/etc/hosts` also matters. 

For example, in `/etc/hosts/`:
```
127.0.0.1 localhost capuchin
``` 

needs to be 

```127.0.0.1 capuchin localhost``` 

in order for interactive jobs to work.
