### ISSUE TITLE
qsub from deleted directory

### ISSUE THREAD

**Issue by stdweird** [adaptivecomputing/torque#333]
if you submit from a directory that has been deleted, qsub happily continues, but jobs will run, but not with correct environment and stdout paths are wrong etc etc: `qstat -f` shows `PBS_O_WORKDIR=` (i.e. empty), and strout/stderr are `Output_Path = submitnode:/sleepjob.sh.o1234` (so the cwd before the `/scriptname.ojobid` is empty)

to reproduce

``` bash
echo 'sleep 10' > /tmp/job.sh
mkdir testdir
cd testdir
rm -Rf $PWD
qsub /tmp/job.sh
qstat -f
```

**Comment by itkovian** [comment]
This is fixed:

~~~~
vsc40075@node2801 (banette) ~> mkdir testdir
vsc40075@node2801 (banette) ~> cd testdir
vsc40075@node2801 (banette) ~/testdir> rm -Rf $PWD
vsc40075@node2801 (banette) ~/testdir> qsub /tmp/job.sh
qsub: Cannot obtain the current directory.
Please submit from a valid directory.
~~~~
