### ISSUE TITLE
syslog.target does not exist anymore

### ISSUE THREAD

**Issue by wpoely86** [adaptivecomputing/torque#342]
b01edc9c36b7 lets the unit files of `pbs_mom` depend on `syslog.target`. This target does not exist any more on up to date RHEL 7 systems. Please drop the require on this target.

**Comment by stdweird** [comment]
@dbeer to clear abotu the gravity of this issue: pbs_mom doesn't start anymore. maybe this needs to be replaced with `syslog.socket`?

**Comment by dbeer** [comment]
I'm not 100% certain how this is supposed to work, but we can look at it.

**Comment by knielson** [comment]
Chad is looking at this right now.

On Fri, Nov 20, 2015 at 1:49 PM, Stijn De Weirdt <notifications@github.com>
wrote:

> @dbeer <https://github.com/dbeer> to clear abotu the gravity of this
> issue: pbs_mom doesn't start anymore. maybe this needs to be replaced with
> syslog.socket?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adaptivecomputing/torque/issues/342#issuecomment-158520137>
> .
>



-- 
[image: Adaptive Computing] <http://www.adaptivecomputing.com>
[image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
+1 801.717.3700 office    +1 801.717.3738 fax
1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
www.adaptivecomputing.com

**Comment by wpoely86** [comment]
Fixed in 8c8d08c53e65f3f4d49f238fae5ce79fb162be1c
