### ISSUE TITLE
qsub should pass proper commandline args to submitfilter

### ISSUE THREAD

**Issue by stdweird** [adaptivecomputing/torque#353]
when using `qsub -C '#ABC' -l nodes=1`, the commandline passed to the submitfilter is only `-C` (it looks like the `#` is interpreted by the subshell as comment?)
we need proper escaping of the commandline passed to submitfilter, or better yet, pass the commandline args as an array.

**Comment by stdweird** [comment]
howto reproduce
* make submitfilter script '/tmp/test'
```python
#!/usr/bin/python
import sys
import os
open('/tmp/output', 'w').write(str(sys.argv))
```
* `chmod +x /tmp/test`
* set it as submitfilter in torque.cfg `SUBMITFILTER /tmp/test`
* submit job using ` qsub -C '#PBS' -l nodes=1 /tmp/test` (submitting the submitfilter itself as jobscript is irrelevant to the problem)
* output in /tmp/output
```
['/tmp/test', '-C']
```

i.e. without the hash and all other options

**Comment by knielson** [comment]
Fixed with these commits

b41c304..547e6eb 6.0-dev -> 6.0-dev
72d25d6..052bc34 develop -> develop
