### ISSUE TITLE
Support for handling (g)zipped log files by tracejob

### ISSUE THREAD

**Issue by itkovian** [adaptivecomputing/torque#354]
Currently, trace job does not consider log files that have been (g)zipped. The reason for the zipping is pretty straightforward: it saves a huge amount of space. The downside is that trace job does not consider them when looking up information about a job.

Would it be possible to use e.g., zlib to transparently handle files that have been compressed?

**Comment by dbeer** [comment]
This should be possible and this would make a great solid contribution to the code.

**Comment by stdweird** [comment]
@itkovian is this fix now?

**Comment by itkovian** [comment]
@stdweird I'm still waiting for some other things before deploying a new build.

**Comment by itkovian** [comment]
Closing, no longer care.
