### ISSUE TITLE
qstat -x returns no output when no jobs are present, breaks XML parsing

### ISSUE THREAD

**Issue by gdevenyi** [adaptivecomputing/torque#357]
I have been playing with the XML outputs of SGE and Torque and noticed that I can’t blindly grab the output of ``qstat -x`` and parse it, because if there’s no jobs, its output is empty.

In comparison, SGE gives a properly formatted XML document:
```
> qstat -xml
<?xml version='1.0'?>
<job_info  xmlns:xsd="http://arc.liv.ac.uk/repos/darcs/sge/source/dist/util/resources/schemas/qstat/qstat.xsd">
  <queue_info>
  </queue_info>
  <job_info>
  </job_info>
</job_info>
```
Perhaps Torque should also dump an empty document that’s parsable?

Reply from @dbeer on mailing list
> Yes, that would probably be proper. I've logged an internal bug for this. If you'd like to be able to track it externally, please log an issue on our github page.

**Comment by dbeer** [comment]
This is fixed by commit f25d517d44e2098d6936f2cbe0b80819964cc00c
