### ISSUE TITLE
torque jobs cannot depend on both array and non-array jobs

### ISSUE THREAD

**Issue by gdevenyi** [adaptivecomputing/torque#358]
Something like:
```
#PBS -W depend=afterok:35487338.gpc-sched-ib0:35487339.gpc-sched-ib0:35487341.gpc-sched-ib0:35487344.gpc-sched-ib0  -W depend=afterokarray:35487333[].gpc-sched-ib0:35487334[].gpc-sched-ib0:35487336[].gpc-sched-ib0:35487337[].gpc-sched-ib0
```

Is not currently allowed, as per @dbeer 
From the mailing list:
> I believe the currently we do not allow the mixing of array dependencies and regular dependencies. We would need to modify the code to allow this. This seems like a reasonable thing to allow, but I believe the code is currently implemented to disallow mixing.

**Comment by dbeer** [comment]
This is fixed by commit 43a9405e2d1ec3784cb22efbc7e25ef62e51ca2a

**Comment by gdevenyi** [comment]
Thanks.

What's the expected format for such dependencies now?

**Comment by dbeer** [comment]
You can probably do more than this, but I do:

qsub script -W depend=afterok:<jobid>,afterokarray:<arrayid>

**Comment by gdevenyi** [comment]
Followup, has this been rolled into a release version yet? I'd like my tool ( https://github.com/pipitone/qbatch ) to warn about hybrid dependencies and mention a version number where this starts working.

**Comment by dbeer** [comment]
This is in the 6.0.2 release, but that release isn't out yet.

**Comment by gdevenyi** [comment]
That's fine, thanks for the info!
