### ISSUE TITLE
Directory permissions are not created correctly on the (re-created) cgroup dirs

### ISSUE THREAD

**Issue by itkovian** [adaptivecomputing/torque#365]
- the first time the cgroup subdirs are created, the permissions are 0755 (correct)
- remove e.g., /sys/fs/cgroup/memory/torque on the node and a pbs_mom thread will recreate them, but with incorrect permissions 0700 (incorrect), as the unmake has been set at that time.
- this happens in 6.0-dev commit f90340b

**Comment by stdweird** [comment]
to clarify, most torque cgroup directories are created when the mom is running (start_exec.c) with `umask(077)`, which is applied on the permission bits by `mkdir()` glibc call (see 2nd paragraph of http://man7.org/linux/man-pages/man2/mkdir.2.html#DESCRIPTION). so either th eumask has to be temporarily set back, or an additional chmod call should be made to set the correct permissions on the cgroup subdirs

**Comment by knielson** [comment]
Thanks for the information

**Comment by dbeer** [comment]
I believe this is fixed by the merge of #367
