### ISSUE TITLE
delete_job_files with $thread_unlink_calls may fail on locked memory

### ISSUE THREAD

**Issue by dvandok** [adaptivecomputing/torque#379]
I've turned on $thread_unlink_calls in torque 4.2.10 and found that the transient job directories were not removed.

Through some debugging I discovered that the mom locks itself into main memory (probably a good idea) through memlock; but the worker threads that take care of the deletion change user identity to the owner of the job. The `ulimit -l` is 64kB, but for root it's not enforced. However, after the identity switch it *is* enforced and the first time `malloc()` tries to `brk()` or `mmap()` it will fail with EAGAIN because too much memory is locked already.

The POSIX standard for threads dictates that all threads should change user id, so it seems best to relegate the deletion of worker directories to a subprocess with a `fork()` rather than using a thread...

For now we've worked around the limitation by increasing the limit on locked memory.

**Comment by dbeer** [comment]
You're right on with this one. Since the piece that executes this is conditional, we'll move just that piece happen in a child. We definitely don't want to be setting the user on the main process.

**Comment by dbeer** [comment]
You are still right, but after a closer look at the code this is fixed in 5.0-dev, 5.1-dev, 6.0-dev, and develop. Whenever you upgrade this issue will be resolved.
