### ISSUE TITLE
Feature request: set hierarchical memory limits in cgroups

### ISSUE THREAD

**Issue by itkovian** [adaptivecomputing/torque#383]
Hi,

It would be nice to have memory cgroup limits set on the torque cgroup, not just on the job cgroup(s). This would ensure the hierarchy (use_hierarchy is set to 1) would honour these limits.

The limits could be set tot what is actually available for the jobs, so e.g., RAM - reserved kernel memory - reserved other stuff (like the GPFS page pool), etc. The mewsw limit could be set to this plus the available swap space.

The underlying idea is to have the torque cgroup kill tasks, before OOM killer comes by.

-- Andy

**Comment by dbeer** [comment]
I think this is a good feature request. I created an internal ticket to track it, and we'll update this one as it progresses. 

I'm thinking that we could add a setting to the mom to control this, something like:

$percentage_of_memory_for_jobs 90

And that would cause the mom to set the Torque memory limit at 90% of the memory on the machine, as well as setting use_hierarchy. 

This would also cause the mom to only report 90% of the memory available, so that the node isn't scheduled into conflicts. 

Does that sound like something that'd meet the use case you're thinking of?

**Comment by stdweird** [comment]
@dbeer :+1:  
ideally we can also specify the `memory_for_jobs` as an absolute value, but this will help us with cases where a certain part of the physical memory is reserved for other system services.

**Comment by dbeer** [comment]
We can do it that way - I was just wondering if a percentage would be easier.

**Comment by stdweird** [comment]
maybe by hand it's easier in percentage, but we generate the mom configs, and actually have all the data we need to compute the exact value. percentages also typically do not work on systems with different memory size anyway (eg a 1% on a 512GB systems vs 10% on a 64GB one; and you'd need to support floats).

**Comment by itkovian** [comment]
Any progress here, @dbeer?

**Comment by dbeer** [comment]
This has not been done yet, but we anticipate releasing it with 6.0.3

**Comment by itkovian** [comment]
Afaik, this is done.

~~~~
[root@node2801 torque]# cat memory.memsw.limit_in_bytes
4294967296
[root@node2801 torque]# cat memory.limit_in_bytes
2147483648
~~~~

**Comment by stdweird** [comment]
@itkovian how is it configured?

**Comment by itkovian** [comment]
This is the default. So no additional action required. The rest I need to figure out how to set up in our env.

**Comment by stdweird** [comment]
what does that mean "default"? where do the values come from?
maybe with https://github.com/adaptivecomputing/torque/commit/14ae082931f8f2013ecf1053572f8f1e5d07878f?

**Comment by itkovian** [comment]
Actually, the values set by default are wrong.

~~~~
[root@node2801 torque]# cat memory.limit_in_bytes
2147483648
[root@node2801 torque]# cat memory.memsw.limit_in_bytes
4294967296
[root@node2801 torque]# free
              total        used        free      shared  buff/cache   available
Mem:        4046908      216080     2978264      199256      852564     3343188
Swap:       4194300           0     4194300
~~~~

So the memsw.limit_in_bytes is set to the amount of swap. But that's not what it means. It actually means RAM + SWAP that should be available to processes.

**Comment by itkovian** [comment]
Hmm, after restarting pbs_mom again, it's back to not being set :(

**Comment by dbeer** [comment]
Sorry, I forgot to update this issue after checking in the fix. We added the parameters $max_physical_memory and $max_swap_memory to change what the mom reports to the server about itself. This change will be released with 6.1.2 and 6.0.4.

**Comment by stdweird** [comment]
@dbeer but does it also set this as limits in the torque cgroup?

**Comment by dbeer** [comment]
It doesn't set it on the cgroup, but it restricts what Moab will schedule, so it should effectively achieve it. For example, if a machine with 32 gb sets the limit to 30 gb, then Moab will never allocate more than 30 gb to jobs on that node. We can add this to the cgroup if necessary, but I think that doing it this way achieves the end result.

**Comment by stdweird** [comment]
@dbeer ideally the mom can also set it in the cgroup. it's what makes sense: the advertise limits are real limits.

**Comment by dbeer** [comment]
Sounds good. We can add this to the torque cgroup.

**Comment by itkovian** [comment]
Has this been done?

**Comment by itkovian** [comment]
Ping on this?

**Comment by mej** [comment]
Just FYI @itkovian, @dbeer is no longer with Adaptive Computing.  Hopefully someone else at @actorquedeveloper (or @ac-autogit or @acvizi) will be able to pick up the issue and run with it.  There haven't been any new pushes since April, and February before that (by @dbeer), so...I'm not really sure who's left doing development on TORQUE....  :-\

**Comment by wpoely86** [comment]
What also would be nice, related to this if we could make one extra step in the cgroup hierarchy:
```
memory/torque/<username>/<jobid>
```
With this, we can restrict a user who logs in with ssh to only the resources that have been allocated to his/her jobs. I'm especially thinking about GPU's here. `pbsdsh` does the right thing but ordinary ssh gives the users access to all resources on the node.

**Comment by itkovian** [comment]
I am going to close this, seems like nothing is moving here anyway.
