### ISSUE TITLE
qsub still drops the prefix provided by -C from the list of submitfilter arguments.

### ISSUE THREAD

**Issue by itkovian** [adaptivecomputing/torque#401]
See also #353, which was reported fixed.

The arguments following a `-C #PBSPREFIX` are now passed on, but `#PBSPREFIX` still is not in the argument list. It is not clear why this was considered fixed.

Tested using the following submitfilter:

~~~~{.python}
#!/usr/bin/python
import sys
import os
open('/tmp/output', 'w').write(str(sys.argv))
~~~~

Submitted the job using

~~~~
echo "sleep 10" | qsub -C '#PBSPREFIX' -l nodes=1
~~~~

Output now has

~~~~
['/tmp/test', '-C', '-l', 'nodes=1']
~~~~

So the `#PBSPREFIX` is gone. Is this expected/desired behaviour, and if so, why?

**Comment by dbeer** [comment]
I'm not sure why the argument wasn't being passed. This should now be fixed by 7b3a28087d12645c6e0dbf1d77dd430c73f03f4d

**Comment by itkovian** [comment]
This is fixed, indeed.

With a changed submit filter:
~~~~
vsc40075@node2801 (banette) ~> echo "sleep 10" | qsub -C '#PBSPREFIX' -l nodes=1
vsc40075@node2801 (banette) ~> cat /tmp/output
['/tmp/submitfilter.test.py', '-C', '#PBSPREFIX', '-l', 'nodes=1']vsc40075@node2801 (banette) ~>
~~~~

**Comment by dbeer** [comment]
I'm glad you were able to confirm the fix.
