### ISSUE TITLE
torque.setup error

### ISSUE THREAD

**Issue by Antsypc** [adaptivecomputing/torque#422]
I got some syntax error While I execute `./torque.setup root` in Ubuntu 14.04.  So, I change some code:
```
function usage
{ ... }

function logit
{ ... }
```

to:
```
usage()
{ ... }
logit()
{ ... }
```
Finally, I got right result.

**Comment by PatrickDouglasCP** [comment]
Which version of torque you get this error?

**Comment by acvizi** [comment]
Change the first line of the original torque.setup from #!/bin/sh to #!/bin/bash. /bin/sh and /bin/bash are not the same on that distro.
