### ISSUE TITLE
where are the torque mailing lists?

### ISSUE THREAD

**Issue by jefftemplon** [adaptivecomputing/torque#452]
Sorry to open an issue here, but an email to adaptive computing has gone unanswered for over a week.  The mailing lists have disappeared from the site:

http://www.adaptivecomputing.com/support/download-center/torque-download/mailing-lists/

clicking the links there generate "page not found" errors.

**Comment by acvizi** [comment]
The mailing lists have been been restored. Our apologies for the delay in getting them back up.
